### ISSUE TITLE
Add studies' phenotypic data BIDS TSV transformation scripts

### ISSUE THREAD

**Issue by ericearl** [ericearl/dataset-phenotypes#12]
Perhaps call them `tabular_data.py` or `data_convert.py` or something similar for each study independently.

**Comment by Arshitha** [comment]
@ericearl - I'm working on the ABCD data files right now and I'll open a PR for it on Mon. Just mentioning here so we don't have two people working on the same thing!

**Comment by ericearl** [comment]
@Arshitha awesome and thanks for letting me know! I was going to tackle this Monday, so I'll just reach out to you on Monday or Tuesday instead.

**Comment by ericearl** [comment]
I'm going to split this issue out with separate issues and refer back to this one.
