### ISSUE TITLE
ABCD data dictionaries that don't have a corresponding tabular data file 

### ISSUE THREAD

**Issue by Arshitha** [ericearl/dataset-phenotypes#30]
A total of 120 dictionaries don't have a corresponding data file in the ABCD Release 4.0 tabular data package (see attached file). Further investigation required as to why. Maybe someone else can download the data package and run the `data_convert.py` script before we look into it further? 

[data_dictionaries_without_data_files.txt](https://github.com/ericearl/dataset-phenotypes/files/10798707/data_dictionaries_without_data_files.txt)

**Comment by ericearl** [comment]
Discussed this offline yesterday and @Arshitha will reach out to the NDA with what appear to be necessary corrections due to filename typos mostly. Closing this as it is not an issue we have control over.
