### ISSUE TITLE
ABCD data files without corresponding data dictionaries

### ISSUE THREAD

**Issue by Arshitha** [ericearl/dataset-phenotypes#31]
I found 14 tabular data files that don't have a corresponding data dictionaries. See attached for the list. Requires further investigation and testing.
[data_files_without_dictionaries.txt](https://github.com/ericearl/dataset-phenotypes/files/10798725/data_files_without_dictionaries.txt)

**Comment by ericearl** [comment]
Discussed this offline yesterday and @Arshitha will reach out to the NDA with what appear to be necessary corrections due to filename typos mostly. Closing this as it is not an issue we have control over.
