### ISSUE TITLE
Draft a phenotypic data browsing, filtering, and selection GUI

### ISSUE THREAD

**Issue by ericearl** [ericearl/dataset-phenotypes#5]
## Concept

A browsable, filterable, searchable GUI for selecting fields of interest from any data dictionary (or possibly all data dictionaries).

## Inputs

The GUI would take as input this repository. It would read from all the available data dictionaries within `<STUDY>/phenotype/` subfolders, as output by `dictionary.py` scripts.

## Drafts

Please insert draft concepts/ideas into this Google Slides deck here:

https://docs.google.com/presentation/d/1OWgNupUz2FyKCEzoAjjDtgunaiWHmjT1ArG1asgndig/edit?usp=sharing

## Implementation

I recommend using [PySimpleGUI](https://www.pysimplegui.org/en/latest/) as I know it works well and is simple and stable and built in Python. Concepts can of course be drawn and pictured, or drafted, or even just a messy draft on a napkin.

## Outputs

As output, you should receive a small data dictionary subset of the selected fields of interest. You should also be able to "auto-save" progress as you click so if the window closes you don't lose a bunch of reading and selection work.

## The dream

In the far-flung future, this would also integrate with BIDS TSVs to provide a sneak preview to the user what the distribution of data points are. Like if it were a Yes/No question, then how many Yes and how many No are in the dataset?

**Comment by ericearl** [comment]
I forgot to add a nice-looking example of something like this from New Relic: https://docs.newrelic.com/attribute-dictionary/

**Comment by JessyD** [comment]
[Here](https://github.com/RobertoFelipeSG/BrainHack2022/blob/main/BrainHack22_GUI.py) is a draft for the GUI

**Comment by ericearl** [comment]
@RobertoFelipeSG's Drafted hackathon GUI added to the repo with commit 8a3fc4fb9b1e0ed151fc50fc8201cb768d0ed503.
